name: "Build Debian image"
description: "Build Debian Docker image for a given architecture"

inputs:
  arch:
    description: "Hardware architecture"
    required: true
    default: "multiarch"
  version:
    description: "Debian release version"
    required: true

runs:
  using: "composite"
  steps:
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
    -
      name: Inspect builder
      shell: sh
      run: |
        echo "Name:      ${{ steps.buildx.outputs.name }}"
        echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
        echo "Status:    ${{ steps.buildx.outputs.status }}"
        echo "Flags:     ${{ steps.buildx.outputs.flags }}"
        echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
    -
      name: Build Debian
      shell: sh
      run: |
        make build-debian platform=${{ inputs.arch }} version=${{ inputs.version }}
