name: multiarch

on:
  push:
  workflow_dispatch:

jobs:

  build-debian:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        debian_version:
          [
            "4",
            "5",
            "6",
          ]
      max-parallel: 1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Debian using Docker Buildx
        uses: ./.github/actions/build-debian-image
        with:
          arch: multiarch
          version: ${{ matrix.debian_version }}

  build-python-debian-4:
    needs: build-debian
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          [
            "2.6",
            "2.6-ucs2",
            "2.7",
            "2.7-ucs2",
            "3.1",
            "3.1-ucs2",
            "3.2",
            "3.2-ucs2",
            "3.3",
            "3.4",
            "3.5",
            "3.6",
            "3.7",
            "3.8",
            "3.9",
          ]
      max-parallel: 1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Python using Docker Buildx
        uses: ./.github/actions/build-python-image
        with:
          arch: multiarch
          base: debian:4
          version: ${{ matrix.python_version }}

  build-python-debian-5:
    needs: build-python-debian-4
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          [
            "2.6",
            "2.6-ucs2",
            "2.7",
            "2.7-ucs2",
            "3.1",
            "3.1-ucs2",
            "3.2",
            "3.2-ucs2",
            "3.3",
            "3.4",
            "3.5",
            "3.6",
            "3.7",
            "3.8",
            "3.9",
          ]
      max-parallel: 1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Python using Docker Buildx
        uses: ./.github/actions/build-python-image
        with:
          arch: multiarch
          base: debian:5
          version: ${{ matrix.python_version }}

  build-python-debian-6:
    needs: build-python-debian-5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          [
            "2.6",
            "2.6-ucs2",
            "2.7",
            "2.7-ucs2",
            "3.1",
            "3.1-ucs2",
            "3.2",
            "3.2-ucs2",
            "3.3",
            "3.4",
            "3.5",
            "3.6",
            "3.7",
            "3.8",
            "3.9",
          ]
      max-parallel: 1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Python using Docker Buildx
        uses: ./.github/actions/build-python-image
        with:
          arch: multiarch
          base: debian:6
          version: ${{ matrix.python_version }}
